### ISSUE TITLE
Grasping not working well

### ISSUE THREAD

**Issue by fbottarel** [hsp-panda/panda_grasp_server#1]
The grasping command currently being used in the program is not working correctly. 

At the moment, the grasp is implemented by simply moving the hand joints to zero. 
```
    def close_gripper(self):
        joint_goal = self._move_group_hand.get_current_joint_values()
        if joint_goal[0] > 0.03 and joint_goal[1] > 0.03:
            return self.command_gripper(0.0)
        else:
            rospy.loginfo("gripper already closed")
            return False
```
This approach, however, does not work reliably since the robot does not actually apply any force once it reaches position, and it is very hard to maintain friction. In fact, it works well on squishy objects, not so well on harder ones like the tin cans. As far as I have observed, the actual behavior is something like 

- command: move aperture to 0
- fingers close until they reach the surface 
- the hand strain gauge feels the effort, and once the configured threshold is reached the movement stops
- movement is deemed as failed and the low level controller aborts the trajectory execution
- position control is deactivated
- fingers open a couple millimiters (not sure why, probably to release the strain on the sensor)

Result: unreliable grasping. 

### Solution hypothesis

It is not clear to me how to perform grasping actions within the MoveIt! framework. However, `franka_gripper` features an action server called `/franka_gripper/grasp` that directly triggers the `libfranka` grasp callback. Info can be found [here](https://frankaemika.github.io/docs/franka_ros.html#franka-gripper). 

By testing the action with 
```
rosrun actionlib axclient.py /franka_gripper/grasp
```
it looks like there is access to the nice `libfranka` parameters such as force and epsilon. 
![image](https://user-images.githubusercontent.com/33027628/97482950-20519a00-1957-11eb-9157-a3f48bb04e63.png)

If a realistic grasp width is given (with relative upper and lower thresholds) the action makes the gripper keep its hold on the object and grasping is way more reliable. 

I will **reimplement** the grasp callbacks according to these findings. @lornat75 @xEnVrE this was a massive oversight on my part when this code was first written, I will have to perform experiments again since this is probably the reason many of the grasps failed in the first place...

NOTE: I have switched back to using the rigid fingers. Not sure how well this translates to the soft fingers, since they absorb force by deformation.

**Comment by fbottarel** [comment]
Update: 
while using the `/franka_gripper/grasp` action, position control is kept active **only** if the action is successful. If not, the position control is released and the fingers are not applying any force. 

The behaviour of the action is the following:
- the gripper will try to close completely
- when the gripper detects a resisting force of over `goal.force` Newtons, it will stop moving
- if `(goal.width - goal.epsilon.inner) < current_width < (goal.width + goal.epsilon.outer)` the actions is registered as successful, and the gripper will maintain its hold
- otherwise, the action is registered as failed and the gripper force is released 

Example: 
```
rostopic pub /franka_gripper/grasp/goal franka_gripper/GraspActionGoal "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
goal_id:
  stamp:
    secs: 0
    nsecs: 0
  id: ''
goal:
  width: 0.04
  epsilon:
    inner: 0.005
    outer: 0.005
  speed: 0.1
  force: 0.5"
```

will fail if trying to grasp an object with width < 3.5 cm or width > 4.5, and will succeed otherwise. 

```
rostopic pub /franka_gripper/grasp/goal franka_gripper/GraspActionGoal "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
goal_id:
  stamp:
    secs: 0
    nsecs: 0
  id: ''
goal:
  width: 0.0
  epsilon:
    inner: 0.08
    outer: 0.01
  speed: 0.1
  force: 0.5"
```

will **always** succeed, no matter if something is actually grasped or not.
